data:
    n_splits: 5
    train_path: data/train_pororo.csv
    test_path: data/test_data.csv
    entity_marker_mode: typed_entity_marker
    entity_marker_num: 18
    
model:
    model_name : klue/roberta-large
    data_class : CLSDataset_pororo
    model_class : LastHiddenLSTMModel
    trainer: BaselineTrainer
    saved_dir: roberta_larget_typed_entmarker_token_weighted_CE_LSTM
    loss : WeightedCEloss
    metric_list:
        metric1 : klue_re_micro_f1
        metric2 : klue_re_auprc
    optimizer : AdamW
    dropout_rate : 0.1

train:
    seed: 42
    gpus: 1
    batch_size: 32
    max_epoch: 5
    learning_rate: 1e-5
    logging_step: 1
    max_length : 270