data:
    n_splits: 5
    train_path: data/train.csv
    test_path: data/test_data.csv
    weighted: True
    
model:
    model_name : klue/bert-base
    data_class : BaselineDataset
    model_class : BaselineModel
    trainer: SimCSEBaselineTrainer
    saved_dir: SimCSEBaseline
    loss : SimCSELoss
    metric_list:
        metric1 : klue_re_micro_f1
        metric2 : klue_re_auprc
    optimizer : AdamW
    dropout_rate : 0.1

train:
    seed: 42
    gpus: 1
    batch_size: 2
    max_epoch: 10
    learning_rate: 5e-5
    logging_step: 1
    max_length : 270
    sim_cse_temperature: 0.1